version: '3.3'
services:
  rproxy: 
    image: nginx:latest
    container_name: nginx_rproxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/data/www
      - ./etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
  mykeycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: mykeycloak
    restart: unless-stopped
    entrypoint: "/opt/keycloak/bin/kc.sh"
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
      - KC_HTTP_RELATIVE_PATH=/auth
